# run grunt yaml to create package.json
# TODO: Add comments
---
  name: "node-startup"
  description: "node.js startup seed"
  version: "0.0.1"
  homepage: ""
  author: 
    name: "Michael Benin"
    email: "michaellouisbenin@gmail.com"
    url: ""
  contributors: 
    - 
      name: ""
      email: ""
      url: ""
  repository: 
    type: "git"
    url: "null"
  bugs: 
    url: "null/issues"
  licenses: 
    - 
      type: "MIT"
  main: "Gruntfile.js"
  engines: 
    node: "*"
  scripts: 
    #preinstall: ""
    postinstall: "npm dedupe && ./node_modules/.bin/grunt browserDependencies copy browserify:modern sass htmlcompressor:development"
    pretest: "./node_modules/.bin/grunt yaml"
    test: "./node_modules/.bin/grunt test"
    #posttest: ""
    prestart: "./node_modules/.bin/grunt prod"
    start: "node server/init.js development"
    #poststart: ""
    precommit: "npm test"
    dev: "./node_modules/.bin/grunt dev"
    dev-unit-test: "./node_modules/.bin/grunt dev-unit-test"
    yaml2json: "./node_modules/.bin/grunt yaml"
  dependencies:
    #awssum-amazon-ec2: "^1.4.0"
    backbone.localstorage: "^1.1.7"
    backbone-relational: "0.8.8"
    backbone.touch: "0.4.0"
    body-parser: "1.5.2"
    bluebird: "^1.2.4"
    #cors: "2.4.1"
    compression: "1.0.9"
    cookie-parser: "1.3.2"
    express: "4.7.2"
    engine.io: "1.4.0"
    engine.io-client: "1.4.0"
    enquire.js: "2.1.1"
    errorhandler: "1.1.1"
    #express-jwt: "^0.1.1"
    #connect-ensure-login: "^0.1.1"
    cozy-slug: "^0.1.2"
    pluralize: "^0.0.7"
    #fb: "^0.7.0"
    #twitter: "^0.2.9"
    #instagram-node-lib: "^0.1.1"
    #supervisor: "^0.5.6"
    googleapis: "^0.4.7"
    #aws-sdk: "^2.0.0-rc5"
    #connect-redis: "^1.4.6"
    #connect-pg: "^1.1.5"
    urlencode: "0.2.0"
    hbs: "2.7.0"
    #es6-promise: "^0.1.1"
    moment: "^2.4.0"
    underscore: "^1.5.2"
    #scriptjs: "^2.4.0"
    glob: "4.0.5"
    npid: "^0.3.2"
    backbone: "^1.1.0"
    #backbone-sql: "^0.5.4"
    #backbone-orm: "^0.5.5"
    #backbone-rest: "^0.5.2"
    #backbone-http: "^0.5.3"
   # backbone-mongo: "^0.5.4"
    backbone-validation: "^0.9.1"
    backbone.epoxy: "1.2.0"
    #connect-html-minifier: "^0.0.1"
    express-bunyan-logger: "^0.0.2"
    #rollbar: "^0.2.9"
    #string-escape: "^0.3.0"
    bunyan: "0.22.1"
    velocity-animate: "0.11.2"
    #keystone: "^0.2.4"
  devDependencies:
    compass-mixins: "0.12.3"
    node-sass: "0.9.3"
    husky: "0.6.0"
    jit-grunt: "0.7.0"
    grunt-cli: "^0.1.13"
    chai: "^1.9.0"
    sinon: "^1.8.2"
    mocha: "^1.17.1"
    grunt: "^0.4.1"
    grunt-env: "^0.4.1"
    grunt-express-server: "^0.4.13"
    grunt-browserify: "2.1.4"
    grunt-nodemon: "^0.2.1"
    grunt-contrib-watch: "^0.6.1"
    grunt-mocha: "^0.4.0"
    grunt-extract-sourcemap: "0.1.12"
    grunt-mocha-test: "^0.10.0"
    grunt-contrib-jshint: "0.10.0"
    grunt-contrib-copy: "^0.4.1"
    grunt-contrib-clean: "^0.4.1"
    grunt-contrib-compass: "0.9.1"
    grunt-contrib-cssmin: "^0.6.1"
    grunt-htmlcompressor: "0.1.8"
    grunt-jsvalidate: "^0.2.1"
    grunt-jsbeautifier: "0.2.7"
    grunt-scss-lint: "0.3.2"
    #grunt-smushit: "^0.4.2"
    grunt-contrib-uglify: "0.5.1"
    grunt-sass-convert: "0.2.0"
    grunt-sass: "0.14.1"
    grunt-spritesmith: "2.1.0"
    grunt-contrib-jscs: "0.1.8"
    grunt-plato: "1.2.0"
    grunt-concurrent: "^0.3.0"
    hbsfy: "^1.3.2"
    request: "2.40.0"
    #requireify: "^0.1.2"
    #promethify: "^0.1.0"
    grunt-docco2: "^0.1.1"
    grunt-styleguide: "^0.2.6"
    #grunt-html-validation: "^0.1.10"
    #grunt-uncss: "^0.1.5"
    grunt-browser-dependencies: "^0.1.2"
    jshint-stylish: "^0.1.3"
    #grunt-aws: "^0.3.0"
    time-grunt: "^0.2.9"
    #grunt-open: "0.2.3"
    #grunt-invalidate-cloudfront: "^0.1.4"
    chai: "^1.8.1"
    grunt-webdriver: "^0.4.0"
    jquery: "^2.1.0"
    jquery.cookie: "1.4.1"
    grunt-yaml: "^0.4.0"
    #grunt-phonegap: "^0.10.1"
    grunt-node-inspector: "0.1.5"
    open: "^0.0.4"
  keywords: []
#  promethify:
#    basedir: "client_modules/external"
#    hostname: "cdn.yourwebsite.com"
#    outputDir: "built/static/js/"
#    outputDeployPath: "static/project/releases"
#    port: 8089
  browserDependencies:
    external:
      dir: "client_modules/external"
      files: 
        - 
          labjs-2.0.3.js: "https://raw.github.com/getify/LABjs/master/LAB.min.js"
        - 
          labjs-debug-2.0.3.js: "https://raw.github.com/getify/LABjs/master/LAB-debug.min.js"
        - 
          html5shiv-3.6.2.js: "https://raw.github.com/aFarkas/html5shiv/master/dist/html5shiv.js"
        -
          selectivizr-v1.0.3b.js: "https://raw.githubusercontent.com/keithclark/selectivizr/ed2f5e3e56f059ad256cc921e24ecc0e1855f18a/selectivizr.js"
        -
          css3-mediaqueries-0.9.js: "https://raw.githubusercontent.com/livingston/css3-mediaqueries-js/534c91a3407745e256150ec5e732d052a7c7d2b0/css3-mediaqueries.js"
        - 
          fastclick-0.6.9.js: "https://raw.github.com/ftlabs/fastclick/98873597601b1a095cec2b93d01667d4b4797dfe/lib/fastclick.js"
        - 
          match-media-polyfill.js: "https://raw.github.com/weblinc/media-match/master/media.match.js"
        - es5-polyfill.js: "https://raw.github.com/inexorabletash/polyfill/master/es5.js"